USE TallerDB
--Crea datatypes de la tabla vehiculos
CREATE TYPE MatriculaType FROM VARCHAR(10) NOT NULL
CREATE TYPE MarcaType FROM VARCHAR(50) NOT NULL
CREATE TYPE ModeloType FROM VARCHAR(50) NOT NULL
CREATE TYPE AnoMatriculacionType FROM INT NOT NULL
CREATE TYPE KilometrajeType FROM INT NOT NULL
CREATE TYPE CombustibleType FROM VARCHAR(10) NOT NULL
CREATE TYPE TransmisionType FROM VARCHAR(10) NOT NULL
CREATE TYPE PotenciaType FROM INT NOT NULL

--Crea datatypes de la tabla clientes
USE TallerDB
CREATE TYPE NIFType FROM VARCHAR(9) NOT NULL
CREATE TYPE NombreType FROM VARCHAR(100) NOT NULL
CREATE TYPE Apellido1Type FROM VARCHAR(100) NOT NULL
CREATE TYPE Apellido2Type FROM VARCHAR(100) NOT NULL
CREATE TYPE PoblacionType FROM VARCHAR(100) NOT NULL
CREATE TYPE CPType FROM VARCHAR(10) NOT NULL
CREATE TYPE TelefonoType FROM VARCHAR(20)NOT NULL
CREATE TYPE EmailType FROM VARCHAR(100) NOT NULL
GO

--Crea datatypes de la tabla facturas
USE TallerDB
CREATE TYPE NumFacturaType FROM VARCHAR(36) NOT NULL
CREATE TYPE FechaFacturaType FROM DATE NOT NULL
CREATE TYPE ImporteType FROM DECIMAL(10, 2) NOT NULL
GO

--Crea datatypes de la tabla reparaciones
USE TallerDB
CREATE TYPE FechaReparacionType FROM DATE
CREATE TYPE DescripcionReparacionType FROM VARCHAR(255) NOT NULL
CREATE TYPE ValorMaterialesType FROM DECIMAL(10, 2) NOT NULL
CREATE TYPE HorasReparacionType FROM DECIMAL(3, 2) NOT NULL
--CREATE TYPE HorasReparacionType FROM DECIMAL(3, 2) DEFAULT 0.5 CHECK (HorasReparacion >= 0.25)
GO
