USE TallerDB

SELECT TOP (1000) [ClienteID]
      ,[NIF]
      ,[Nombre]
      ,[Apellido1]
      ,[Apellido2]
      ,[Poblacion]
      ,[CP]
      ,[Telefono]
      ,[Email]
  FROM [TallerDB].[dbo].[Clientes]

SELECT TOP (1000) [FacturaID]
      ,[NumFactura]
      ,[FechaFactura]
      ,[Importe]
      ,[IVA]
      ,[ImporteTotal]
      ,[ClienteID]
      ,[VehiculoID]
  FROM [TallerDB].[dbo].[Facturas]

  SELECT TOP (1000) [ReparacionID]
      ,[FechaReparacion]
      ,[Matricula]
      ,[DescripcionReparacion]
      ,[ValorMateriales]
      ,[HorasReparacion]
      ,[VehiculoID]
  FROM [TallerDB].[dbo].[Reparaciones]

  SELECT TOP (1000) [VehiculoID]
      ,[Matricula]
      ,[Marca]
      ,[Modelo]
      ,[AnoMatriculacion]
      ,[Kilometraje]
      ,[Combustible]
      ,[Transmision]
      ,[Potencia]
      ,[ClienteID]
  FROM [TallerDB].[dbo].[Vehiculos]
